from enum import Enum
from pydantic import BaseModel


class BusinessType(Enum):
    FASHION = "FASHION"
    FOOD = "FOOD"
    HEALTH_AND_WELLNESS = "HEALTH_AND_WELLNESS"
    ELECTRONICS_AND_TECH = "ELECTRONICS_AND_TECH"
    BEAUTY_AND_PERSONAL_CARE = "BEAUTY_AND_PERSONAL_CARE"
    AUTOMOTIVE = "AUTOMOTIVE"
    FINANCE_AND_INSURANCE = "FINANCE_AND_INSURANCE"
    ENTERTAINMENT_AND_MEDIA = "ENTERTAINMENT_AND_MEDIA"
    EDUCATION = "EDUCATION"
    HOSPITALITY_AND_TOURISM = "HOSPITALITY_AND_TOURISM"
    AGRICULTURE_AND_FARMING = "AGRICULTURE_AND_FARMING"
    LEGAL_SERVICES = "LEGAL_SERVICES"
    NIGHTLIFE = "NIGHTLIFE"
    PETS_AND_ANIMALS = "PETS_AND_ANIMALS"

